name: Ensure Linting rules upheld

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs: # list of things to do
  eslint:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    permissions:
        contents: read
        security-events: write
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps: # list of steps
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Code Checkout
        uses: actions/checkout@v2
        
      - name: Dependency Installation
        run: bun install --frozen-lockfile

      - name: Code Linting
        run: bun run lint
